server:
  port: 9900
logging:
  level:
    com.netflix.discovery: 'OFF'
    com.netflix.zuul: 'OFF'
endpoints:
  health:
    sensitive: false

eureka:
  instance:
    hostname: 10.200.32.42
    leaseRenewalIntervalInSeconds: 10
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 8761
    registryFetchIntervalSeconds: 5

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ServerListRefreshInterval: 5000
  ConnectTimeout: 3000
  ReadTimeout: 60000

zuul:
  routes:
    stores:
      path: /stores/**
      strip-prefix: false
    customers:
      path: /customers/**
      strip-prefix: false