server:
  port: 0


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  data:
    mongodb:
      uri: ${vcap.services.${PREFIX:}mongodb.credentials.uri:mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/stores}
  rabbitmq:
#    addresses: ${vcap.services.${PREFIX:}rabbitmq.credentials.uri:amqp://${RABBITMQ_HOST:localhost}:${RABBITMQ_PORT:5672}}
    host: ${WORKPC_HOST}
    port: 5655
    username: bout01
#    password: nmwrKv6vG8RIKk6R8MnnIQ==
    password: Password2015

eureka:
  instance:
    instance-id: ${LOCAL_HOST}:stores:9000
    ip-address: ${LOCAL_HOST}
    hostname: ${LOCAL_HOST}
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${LOCAL_HOST}:stores:9000
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    service-url:
      defaultZone: http://${WORKPC_HOST}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 8761
    registryFetchIntervalSeconds: 5

logging:
  level:
    com.netflix.discovery: 'OFF'